/**
 * @author Josh Lobe
 * http://ultimatetinymcepro.com
 */

jQuery(document).ready(function(a){function v(c){a("#search_replace").attr("class","");a("#re_beautify").attr("class","");a("#autocompletion").attr("disabled",!1);b=CodeMirror.fromTextArea(a("#htmlSource")[0],{mode:"text/html",lineNumbers:!0,styleActiveLine:!0,styleSelectedText:!0,highlightSelectionMatches:!0,indentUnit:4});b.focus();b.on("change",function(e){e=b.doc.historySize().undo;var c=b.doc.historySize().redo;0<e?a("#undo").attr("class",""):a("#undo").attr("class","disabled");0<c?a("#redo").attr("class",
""):a("#redo").attr("class","disabled")});b.on("keypress",function(a,c){if(m&&"<"==String.fromCharCode(null==c.which?c.keyCode:c.which)){c.preventDefault();var g=b.getCursor(!1);b.getTokenAt(g);b.replaceRange("<",g);setTimeout(p,50);return!0}});a("#wraptext").is(":checked")?b.setOption("lineWrapping",!0):b.setOption("lineWrapping",!1)}function w(){q.length=0;var c=a("#query").val();if(!c)return!1;if(!b.getSearchCursor(c).findNext())return alert("Nothing Found."),!1;for(var e=b.getSearchCursor(c);e.findNext();)q.push(b.markText(e.from(),
e.to(),"searched"));t!=c&&(r=null);e=b.getSearchCursor(c,r||b.getCursor());if(!e.findNext()&&(e=b.getSearchCursor(c),!e.findNext()))return;b.setSelection(e.from(),e.to());t=c;r=e.to()}function u(a,b){for(var f=0,g=a.length;f<g;++f)b(a[f])}function p(){function c(c){if(""!=c){c=c.replace(/^\s+|\s+$/g,"");g=x.inArray(c)?!0:!1;if(null!=s[c]&&f){var e=s[c].tag;c=d.start+c.length+s[c].cusror}else f&&g?(e=c+" />",c=d.start+c.length+3):(e=f?c+"></"+c+">":c+">",c=d.start+c.length+1);b.replaceRange(e,{line:n.line,
ch:d.start},{line:n.line,ch:d.end});b.setCursor({line:n.line,ch:c});a("body").off("dblclick","option");a("body").off("keydown","select")}}function e(){html_tag=a("#completions_options").find(":selected").text();c(html_tag);l.remove();setTimeout(function(){b.focus()},50)}var f,g;if(!b.somethingSelected()){var n=b.getCursor(!1),d=b.getTokenAt(n);if(0==d.string.indexOf("<")&&0!=d.string.indexOf("</"))d.string=d.string.replace("<",""),d.start++,f=!0;else if(0==d.string.indexOf("</"))d.string=d.string.replace("</",
""),d.start+=2,f=!1;else return;var k=y(d,f);if(k.length){for(var l=a("<div class='completions'>"),h=[],m=0;m<k.length;++m)h+="<option>"+k[m]+"</option>";l.append('<select id="completions_options">'+h+"</select>");a("select option:first-child").attr("selected","selected");l.children().attr("size","10");k=b.cursorCoords();l.css("margin-left",k.left+"px");0<k.top&&(k.top-=550);l.css("margin-top",k.top+"px");a("body").append(l);a("select").focus();a("body").on("dblclick","option",function(){e()});a("body").on("keydown",
"select",function(c){var d=c.keyCode;13==d||32==d||9==d?(c.preventDefault(),e()):27==d?(c.preventDefault(),l.remove(),b.focus()):38!=d&&40!=d&&16!=d&&17!=d&&18!=d&&91!=d&&92!=d&&(l.remove(),b.focus(),39!=d&&37!=d?(a("body").off("dblclick","option"),a("body").off("keydown","select"),setTimeout(p,50)):c.preventDefault())})}}}function y(a,b){function f(a){0==a.indexOf(h)&&g.push(a)}var g=[],h=a.string;b?u(z,f):u(A,f);return g}var h=top.tinymce.activeEditor,t=null,r=null,q=[],m=!0,b=CodeMirror.fromTextArea(a("#htmlSource")[0],
{mode:"text/html",lineNumbers:!0,lineWrapping:!0,styleActiveLine:!0,styleSelectedText:!0,highlightSelectionMatches:!0,indentUnit:4});b.doc.setValue(style_html(h.getContent({format:"html"}),4));b.focus();b.on("change",function(c,e){var f=b.doc.historySize().undo,g=b.doc.historySize().redo;1<f?a("#undo").attr("class",""):a("#undo").attr("class","disabled");0<g?a("#redo").attr("class",""):a("#redo").attr("class","disabled")});b.on("keypress",function(a,e){if(m&&"<"==String.fromCharCode(null==e.which?
e.keyCode:e.which)){e.preventDefault();var f=b.getCursor(!1);b.getTokenAt(f);b.replaceRange("<",f);setTimeout(p,50);return!0}});a("#codemagic_cancel").click(function(){h.windowManager.close()});a("#codemagic_insert").click(function(){window_content=b.doc.getValue();h.setContent(window_content);h.windowManager.close()});a("#undo").click(function(){"disabled"!=a(this).attr("class")&&(className=a("#undo").attr("class"),"disabled"!=className&&b.doc.undo())});a("#redo").click(function(){"disabled"!=a(this).attr("class")&&
b.doc.redo()});a("#search_replace").click(function(){"disabled"!=a(this).attr("class")&&(a("#search_replace").toggleClass("selected"),a("#search_panel").slideToggle("slow",function(){}))});a("#re_beautify").click(function(){"disabled"!=a(this).attr("class")&&(window_html=b.doc.getValue(),b.doc.setValue(style_html(window_html,4)))});a("#wraptext").click(function(){a(this).is(":checked")?b.setOption("lineWrapping",!0):b.setOption("lineWrapping",!1)});a("#autocompletion").click(function(){m=a(this).is(":checked")?
!0:!1});a("#highlighting").click(function(){a(this).is(":checked")?v("htmlSource"):(b.doc.clearHistory(),a("#undo").attr("class","disabled"),a("#redo").attr("class","disabled"),a("#search_replace").attr("class","disabled"),a("#re_beautify").attr("class","disabled"),a("#autocompletion").attr("disabled",!0),b.toTextArea())});a("#search_code").click(function(){w()});a("#replace_code").click(function(){q.length=0;var c=a("#query").val(),e=a("#replace").val();if(c)if(b.getSearchCursor(c).findNext())for(c=
b.getSearchCursor(c);c.findNext();)b.replaceRange(e,c.from(),c.to());else alert("Nothing to Replace.")});var z="a abbr acronym address applet area b base basefont bdo big blockquote body br button caption center cite code col colgroup dd del dfn dir div dl dt em fieldset font form frame frameset h1 h2 h3 h4 h5 h6 head hr html i iframe img input ins isindex kbd label legend li link map menu meta noframes noscript object ol optgroup option p param pre q s samp script select small span strike strong style sub sup table tbody td textarea tfoot th thead title tr tt u ul var".split(" "),
A="a abbr acronym address applet b bdo big blockquote body button caption center cite code colgroup del dfn dir div dl em fieldset font form frameset h1 h2 h3 h4 h5 h6 head html i iframe ins kbd label legend li map menu noframes noscript object ol optgroup option p pre q s samp script select small span strike strong style sub sup table tbody td textarea tfoot th thead title tr tt u ul var".split(" "),x="area base basefont br col dd dt frame hr img input isindex link meta param".split(" "),s={applet:{tag:'applet width="" height=""></applet>',
cusror:8},area:{tag:'area alt="" />',cusror:6},base:{tag:'base href="" />',cusror:7},form:{tag:'form action=""></form>',cusror:9},img:{tag:'img src="" alt="" />',cusror:6},map:{tag:'map name=""></map>',cusror:7},meta:{tag:'meta content="" />',cusror:10},optgroup:{tag:'optgroup label=""></optgroup>',cusror:8},param:{tag:'param name="" />',cusror:7},script:{tag:'script type="">\x3c/script>',cusror:7},style:{tag:'style type=""></style>',cusror:7},textarea:{tag:'textarea cols="" rows=""></textarea>',
cusror:7}};Array.prototype.inArray=function(a){for(var b in this)if(this[b]===a)return!0;return!1}});
